"""Unit tests for core metric_utils functions.

Tests run without scc or git — only pure Python logic is exercised.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from repo_metadata_cli.metric_utils import (
    _is_autogen_file,
    _parse_scc_output,
    get_dep_dir_loc,
)


# ---------------------------------------------------------------------------
# _parse_scc_output
# ---------------------------------------------------------------------------

def test_parse_scc_output_empty_string():
    result = _parse_scc_output("")
    assert result["total"]["lines"] == 0
    assert result["total"]["code"] == 0
    assert result["total"]["blank"] == 0
    assert result["languages"] == []


def test_parse_scc_output_single_language():
    raw = json.dumps([
        {"Name": "Python", "Lines": 100, "Code": 70, "Comment": 10, "Blank": 20, "Count": 3}
    ])
    result = _parse_scc_output(raw)
    assert result["total"]["lines"] == 100
    assert result["total"]["code"] == 70
    assert result["total"]["comment"] == 10
    assert result["total"]["blank"] == 20
    assert result["total"]["files"] == 3
    assert len(result["languages"]) == 1
    assert result["languages"][0]["name"] == "Python"


def test_parse_scc_output_aggregates_multiple_languages():
    raw = json.dumps([
        {"Name": "Python", "Lines": 100, "Code": 80, "Comment": 10, "Blank": 10, "Count": 2},
        {"Name": "Go",     "Lines": 200, "Code": 150, "Comment": 30, "Blank": 20, "Count": 5},
    ])
    result = _parse_scc_output(raw)
    assert result["total"]["lines"] == 300
    assert result["total"]["code"] == 230
    assert result["total"]["files"] == 7
    assert len(result["languages"]) == 2


def test_parse_scc_output_invalid_json_returns_empty():
    result = _parse_scc_output("not json at all")
    assert result["total"]["lines"] == 0
    assert result["languages"] == []


def test_parse_scc_output_not_a_list_returns_empty():
    result = _parse_scc_output(json.dumps({"key": "value"}))
    assert result["total"]["lines"] == 0


def test_parse_scc_output_skips_entries_without_name():
    raw = json.dumps([
        {"Lines": 50, "Code": 40, "Comment": 5, "Blank": 5, "Count": 1},
        {"Name": "Rust", "Lines": 80, "Code": 70, "Comment": 5, "Blank": 5, "Count": 2},
    ])
    result = _parse_scc_output(raw)
    assert result["total"]["lines"] == 80
    assert len(result["languages"]) == 1


# ---------------------------------------------------------------------------
# _is_autogen_file
# ---------------------------------------------------------------------------

def test_is_autogen_dir_match(tmp_path):
    f = tmp_path / "migrations" / "0001_initial.py"
    f.parent.mkdir()
    f.write_text("x = 1")
    assert _is_autogen_file(f, tmp_path, {"migrations"}) is True


def test_is_autogen_dir_no_match(tmp_path):
    f = tmp_path / "src" / "main.py"
    f.parent.mkdir()
    f.write_text("x = 1")
    assert _is_autogen_file(f, tmp_path, {"migrations"}) is False


def test_is_autogen_dir_case_insensitive(tmp_path):
    f = tmp_path / "Generated" / "api.py"
    f.parent.mkdir()
    f.write_text("x = 1")
    assert _is_autogen_file(f, tmp_path, {"generated"}) is True


def test_is_autogen_nested_dir(tmp_path):
    f = tmp_path / "pkg" / "gen" / "types.go"
    (tmp_path / "pkg" / "gen").mkdir(parents=True)
    f.write_text("package gen")
    assert _is_autogen_file(f, tmp_path, {"gen"}) is True


def test_is_autogen_exact_name_package_lock(tmp_path):
    f = tmp_path / "package-lock.json"
    f.write_text("{}")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_exact_name_yarn_lock(tmp_path):
    f = tmp_path / "yarn.lock"
    f.write_text("# yarn")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_exact_name_go_sum(tmp_path):
    f = tmp_path / "go.sum"
    f.write_text("github.com/foo v1.0 h1:abc")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_pattern_pb2(tmp_path):
    f = tmp_path / "user_pb2.py"
    f.write_text("class User: pass")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_pattern_pb_go(tmp_path):
    f = tmp_path / "service.pb.go"
    f.write_text("package service")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_pattern_min_js(tmp_path):
    f = tmp_path / "bundle.min.js"
    f.write_text("!function(){}")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_header_marker(tmp_path):
    f = tmp_path / "api.go"
    f.write_text("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_header_at_generated(tmp_path):
    f = tmp_path / "schema.ts"
    f.write_text("// @generated\nexport type Foo = string;\n")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_regular_file_is_false(tmp_path):
    f = tmp_path / "app.py"
    f.write_text("def main(): pass\n")
    assert _is_autogen_file(f, tmp_path, set()) is False


# ---------------------------------------------------------------------------
# get_dep_dir_loc
# ---------------------------------------------------------------------------

def test_dep_dir_loc_zero_when_no_dep_dirs_exist(tmp_path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("x = 1\n")
    result = get_dep_dir_loc(tmp_path, {"node_modules", "vendor"})
    assert result == 0


def test_dep_dir_loc_zero_for_empty_dep_set(tmp_path):
    vendor = tmp_path / "vendor"
    vendor.mkdir()
    (vendor / "lib.go").write_text("package lib\nfunc F() {}\n")
    result = get_dep_dir_loc(tmp_path, set())
    assert result == 0


def test_dep_dir_loc_returns_int(tmp_path):
    vendor = tmp_path / "vendor"
    vendor.mkdir()
    (vendor / "lib.py").write_text("\n".join(f"x{i} = {i}" for i in range(10)))
    result = get_dep_dir_loc(tmp_path, {"vendor"})
    assert isinstance(result, int)
    assert result >= 0


def test_dep_dir_loc_ignores_non_dep_dirs(tmp_path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("x = 1\n")
    result = get_dep_dir_loc(tmp_path, {"vendor"})
    assert result == 0
