"""Unit tests for core metric_utils functions.

Tests run without scc or git — only pure Python logic is exercised.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from repo_metadata_cli.metric_utils import (
    _is_autogen_file,
    _parse_du_kb,
    _parse_scc_output,
    compute_readme_stats,
    count_chars_in_files,
    detect_license,
    get_dep_dir_loc,
)


# ---------------------------------------------------------------------------
# _parse_scc_output
# ---------------------------------------------------------------------------

def test_parse_scc_output_empty_string():
    result = _parse_scc_output("")
    assert result["total"]["lines"] == 0
    assert result["total"]["code"] == 0
    assert result["total"]["blank"] == 0
    assert result["languages"] == []


def test_parse_scc_output_single_language():
    raw = json.dumps([
        {"Name": "Python", "Lines": 100, "Code": 70, "Comment": 10, "Blank": 20, "Count": 3}
    ])
    result = _parse_scc_output(raw)
    assert result["total"]["lines"] == 100
    assert result["total"]["code"] == 70
    assert result["total"]["comment"] == 10
    assert result["total"]["blank"] == 20
    assert result["total"]["files"] == 3
    assert len(result["languages"]) == 1
    assert result["languages"][0]["name"] == "Python"


def test_parse_scc_output_aggregates_multiple_languages():
    raw = json.dumps([
        {"Name": "Python", "Lines": 100, "Code": 80, "Comment": 10, "Blank": 10, "Count": 2},
        {"Name": "Go",     "Lines": 200, "Code": 150, "Comment": 30, "Blank": 20, "Count": 5},
    ])
    result = _parse_scc_output(raw)
    assert result["total"]["lines"] == 300
    assert result["total"]["code"] == 230
    assert result["total"]["files"] == 7
    assert len(result["languages"]) == 2


def test_parse_scc_output_invalid_json_returns_empty():
    result = _parse_scc_output("not json at all")
    assert result["total"]["lines"] == 0
    assert result["languages"] == []


def test_parse_scc_output_not_a_list_returns_empty():
    result = _parse_scc_output(json.dumps({"key": "value"}))
    assert result["total"]["lines"] == 0


def test_parse_scc_output_skips_entries_without_name():
    raw = json.dumps([
        {"Lines": 50, "Code": 40, "Comment": 5, "Blank": 5, "Count": 1},
        {"Name": "Rust", "Lines": 80, "Code": 70, "Comment": 5, "Blank": 5, "Count": 2},
    ])
    result = _parse_scc_output(raw)
    assert result["total"]["lines"] == 80
    assert len(result["languages"]) == 1


# ---------------------------------------------------------------------------
# _is_autogen_file
# ---------------------------------------------------------------------------

def test_is_autogen_dir_match(tmp_path):
    f = tmp_path / "migrations" / "0001_initial.py"
    f.parent.mkdir()
    f.write_text("x = 1")
    assert _is_autogen_file(f, tmp_path, {"migrations"}) is True


def test_is_autogen_dir_no_match(tmp_path):
    f = tmp_path / "src" / "main.py"
    f.parent.mkdir()
    f.write_text("x = 1")
    assert _is_autogen_file(f, tmp_path, {"migrations"}) is False


def test_is_autogen_dir_case_insensitive(tmp_path):
    f = tmp_path / "Generated" / "api.py"
    f.parent.mkdir()
    f.write_text("x = 1")
    assert _is_autogen_file(f, tmp_path, {"generated"}) is True


def test_is_autogen_nested_dir(tmp_path):
    f = tmp_path / "pkg" / "gen" / "types.go"
    (tmp_path / "pkg" / "gen").mkdir(parents=True)
    f.write_text("package gen")
    assert _is_autogen_file(f, tmp_path, {"gen"}) is True


def test_is_autogen_exact_name_package_lock(tmp_path):
    f = tmp_path / "package-lock.json"
    f.write_text("{}")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_exact_name_yarn_lock(tmp_path):
    f = tmp_path / "yarn.lock"
    f.write_text("# yarn")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_exact_name_go_sum(tmp_path):
    f = tmp_path / "go.sum"
    f.write_text("github.com/foo v1.0 h1:abc")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_pattern_pb2(tmp_path):
    f = tmp_path / "user_pb2.py"
    f.write_text("class User: pass")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_pattern_pb_go(tmp_path):
    f = tmp_path / "service.pb.go"
    f.write_text("package service")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_pattern_min_js(tmp_path):
    f = tmp_path / "bundle.min.js"
    f.write_text("!function(){}")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_header_marker(tmp_path):
    f = tmp_path / "api.go"
    f.write_text("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_is_autogen_regular_file_is_false(tmp_path):
    f = tmp_path / "app.py"
    f.write_text("def main(): pass\n")
    assert _is_autogen_file(f, tmp_path, set()) is False


# ---------------------------------------------------------------------------
# get_dep_dir_loc
# ---------------------------------------------------------------------------

def test_dep_dir_loc_zero_when_no_dep_dirs_exist(tmp_path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("x = 1\n")
    result = get_dep_dir_loc(tmp_path, {"node_modules", "vendor"})
    assert result == 0


def test_dep_dir_loc_zero_for_empty_dep_set(tmp_path):
    vendor = tmp_path / "vendor"
    vendor.mkdir()
    (vendor / "lib.go").write_text("package lib\nfunc F() {}\n")
    result = get_dep_dir_loc(tmp_path, set())
    assert result == 0


def test_dep_dir_loc_returns_int(tmp_path):
    vendor = tmp_path / "vendor"
    vendor.mkdir()
    (vendor / "lib.py").write_text("\n".join(f"x{i} = {i}" for i in range(10)))
    result = get_dep_dir_loc(tmp_path, {"vendor"})
    assert isinstance(result, int)
    assert result >= 0


def test_dep_dir_loc_ignores_non_dep_dirs(tmp_path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("x = 1\n")
    result = get_dep_dir_loc(tmp_path, {"vendor"})
    assert result == 0


# ---------------------------------------------------------------------------
# detect_license (ported from v1)
# ---------------------------------------------------------------------------

def test_detect_license_unknown_when_absent(tmp_path):
    assert detect_license(tmp_path) == "UNKNOWN"


def test_detect_license_mit(tmp_path):
    (tmp_path / "LICENSE").write_text(
        "MIT License\n\nPermission is hereby granted, free of charge, to any person...\n"
    )
    assert detect_license(tmp_path) == "MIT"


def test_detect_license_apache(tmp_path):
    (tmp_path / "LICENSE").write_text("Apache License\nVersion 2.0, January 2004\n")
    assert detect_license(tmp_path) == "APACHE-2.0"


def test_detect_license_gpl3(tmp_path):
    (tmp_path / "COPYING").write_text(
        "GNU GENERAL PUBLIC LICENSE\nVersion 3, 29 June 2007\n"
    )
    assert detect_license(tmp_path) == "GPL-3.0"


def test_detect_license_falls_back_to_filename(tmp_path):
    (tmp_path / "LICENSE-MIT").write_text("some unrecognized header text\n")
    assert detect_license(tmp_path) == "MIT"


# ---------------------------------------------------------------------------
# compute_readme_stats (ported from v1)
# ---------------------------------------------------------------------------

def test_readme_stats_zero_when_absent(tmp_path):
    assert compute_readme_stats(tmp_path) == 0


def test_readme_stats_counts_lines(tmp_path):
    (tmp_path / "README.md").write_text("line1\nline2\nline3\n")
    assert compute_readme_stats(tmp_path) == 3


def test_readme_stats_sums_multiple_readmes(tmp_path):
    (tmp_path / "README.md").write_text("a\nb\n")
    (tmp_path / "README.rst").write_text("c\n")
    assert compute_readme_stats(tmp_path) == 3


# ---------------------------------------------------------------------------
# _parse_du_kb (ported from v1)
# ---------------------------------------------------------------------------

def test_parse_du_kb_normal():
    assert _parse_du_kb("1234\t/some/path") == 1234


def test_parse_du_kb_malformed_returns_zero():
    assert _parse_du_kb("") == 0
    assert _parse_du_kb("not-a-number\tpath") == 0


# ---------------------------------------------------------------------------
# count_chars_in_files (symbols_count)
# ---------------------------------------------------------------------------

def test_count_chars_in_files_empty():
    assert count_chars_in_files([]) == 0


def test_count_chars_in_files_ascii(tmp_path):
    f = tmp_path / "a.py"
    f.write_text("x = 1\n")  # 6 chars
    assert count_chars_in_files([{"path": f, "code": 1}]) == 6


def test_count_chars_in_files_counts_unicode_chars_not_bytes(tmp_path):
    f = tmp_path / "u.py"
    # "# комментарий\nx = 1\n" → 20 characters but 31 bytes in UTF-8
    f.write_text("# комментарий\nx = 1\n", encoding="utf-8")
    assert count_chars_in_files([{"path": f, "code": 1}]) == 20


def test_count_chars_in_files_sums_multiple_and_skips_missing(tmp_path):
    f1 = tmp_path / "a.py"
    f1.write_text("ab\n")   # 3
    f2 = tmp_path / "b.py"
    f2.write_text("cde\n")  # 4
    missing = tmp_path / "nope.py"
    total = count_chars_in_files([
        {"path": f1, "code": 1},
        {"path": f2, "code": 1},
        {"path": missing, "code": 0},
    ])
    assert total == 7
