"""Tests for clean_handwritten_loc (BH) and autogen_in_clean_loc (BI).

The split exists because autogen_loc (H) is measured over the logical_loc file
set while clean_logical_loc (BG) uses a smaller one; subtracting H from BG
over-counts whenever the generated bulk sits in files BG never counted.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from repo_metadata_cli.metric_utils import (
    get_auto_gen_loc,
    get_clean_loc_split,
    get_clean_logical_loc,
)
from repo_metadata_cli.settings import load_app_settings

_PROJECT_ROOT = Path(__file__).parent.parent
_TOML_PATH = _PROJECT_ROOT / "repo_metadata.toml"


def _settings():
    return load_app_settings(_TOML_PATH).metrics


def _split(repo: Path):
    m = _settings()
    return get_clean_loc_split(
        repo,
        exclude_dirs=list(m.clean_scc_exclude_dirs),
        non_code_languages=set(m.clean_non_code_languages),
        autogen_dirs=set(m.autogen_dirs),
    )


def _write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)


scc = pytest.importorskip  # keeps the module importable without scc


@pytest.fixture()
def repo(tmp_path: Path) -> Path:
    """Hand-written code, a generated source file, and a bulky data dump."""
    _write(tmp_path / "app" / "service.py", "\n".join(f"x = {i}" for i in range(40)) + "\n")
    _write(
        tmp_path / "app" / "schema_pb2.py",
        "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        + "\n".join(f"FIELD_{i} = {i}" for i in range(20))
        + "\n",
    )
    # data dump: counted by logical_loc, never by clean_logical_loc.  Long lines
    # give it the shape autogen detection recognises (see _has_generated_shape).
    row = '  {"id": %d, "payload": "%s"},'
    _write(
        tmp_path / "export" / "catalog.json",
        "[\n" + "\n".join(row % (i, "v" * 300) for i in range(200)) + "\n]\n",
    )
    return tmp_path


def test_split_adds_up_to_clean(repo: Path):
    total, generated = _split(repo)
    assert total == get_clean_logical_loc(
        repo,
        exclude_dirs=list(_settings().clean_scc_exclude_dirs),
        non_code_languages=set(_settings().clean_non_code_languages),
    )
    assert 0 <= generated <= total


def test_generated_source_lands_in_the_generated_half(repo: Path):
    total, generated = _split(repo)
    handwritten = total - generated
    # the protobuf stub is generated code, the service module is not
    assert generated >= 20
    assert handwritten >= 40
    assert handwritten + generated == total


def test_data_dump_does_not_inflate_the_generated_half(repo: Path):
    """The JSON dump is outside the clean set, so it must not count in BI —
    this is the whole point of measuring the overlap instead of reusing H."""
    total, generated = _split(repo)
    m = _settings()
    autogen_h = get_auto_gen_loc(repo, set(m.autogen_dirs), set(m.scc_exclude_dirs))
    # H sees the dump (thousands of lines), BI must not
    assert autogen_h > generated
    assert generated < 1000
    # the naive subtraction would go negative — that is the bug BH avoids
    assert total - autogen_h < 0
    assert total - generated > 0


def test_repo_without_generated_files(tmp_path: Path):
    _write(tmp_path / "main.go", "package main\n\nfunc main() {\n\tprintln(1)\n}\n")
    total, generated = _split(tmp_path)
    assert total > 0
    assert generated == 0
