"""Tests for clean_logical_loc (BG) and the extended autogen detection.

Detector unit tests run without scc; the integration test at the bottom uses
scc via the metric class (scc is a hard dependency of the pipeline).
"""

from __future__ import annotations

from pathlib import Path
from subprocess import run

import pytest

from repo_metadata_cli.allowed_files import AllowedFiles
from repo_metadata_cli.base_metric import RepoContext
from repo_metadata_cli.config import AllowedFilesConfig
from repo_metadata_cli.metric_utils import (
    _is_android_res_xml,
    _is_autogen_file,
    _is_sql_dump,
    get_clean_logical_loc,
)
from repo_metadata_cli.metrics.loc import CleanLogicalLocMetric, LogicalLocMetric
from repo_metadata_cli.settings import load_app_settings

_PROJECT_ROOT = Path(__file__).parent.parent
_TOML_PATH = _PROJECT_ROOT / "repo_metadata.toml"


# ---------------------------------------------------------------------------
# Extended header markers + scaffold whitelist
# ---------------------------------------------------------------------------

def test_header_marker_past_line_five(tmp_path):
    """Generator banners placed after a licence block (e.g. line 10) are caught."""
    lines = ["// licence line %d" % i for i in range(9)]
    lines.append("// NOTE: This class is auto generated by a code generator.")
    f = tmp_path / "api.ts"
    f.write_text("\n".join(lines) + "\nexport const x = 1\n")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_header_marker_generated_using(tmp_path):
    f = tmp_path / "strings.swift"
    f.write_text("// swiftlint:disable all\n// Generated using a template\nlet a = 1\n")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_header_marker_at_generated(tmp_path):
    f = tmp_path / "module.js"
    f.write_text("/**\n * @generated\n */\nmodule.exports = {}\n")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_scaffold_settings_not_autogen(tmp_path):
    """Framework scaffolds are created by a tool but hand-edited afterwards."""
    f = tmp_path / "settings.py"
    f.write_text(
        '"""\nSettings for the project.\n\n'
        "Generated by 'django-admin startproject' using Django.\n"
        '"""\nDEBUG = True\n'
    )
    assert _is_autogen_file(f, tmp_path, set()) is False


def test_scaffold_spec_helper_not_autogen(tmp_path):
    f = tmp_path / "spec_helper.rb"
    f.write_text(
        "# This file was generated by the `rails generate rspec:install` command.\n"
        "RSpec.configure do |config|\nend\n"
    )
    assert _is_autogen_file(f, tmp_path, set()) is False


# ---------------------------------------------------------------------------
# Directory pairs + generator footprints
# ---------------------------------------------------------------------------

def test_alembic_versions_is_autogen(tmp_path):
    d = tmp_path / "alembic" / "versions"
    d.mkdir(parents=True)
    f = d / "20200101_add_table.py"
    f.write_text('"""add table\n\nRevision ID: abc\n"""\n')
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_bare_versions_dir_is_not_autogen(tmp_path):
    d = tmp_path / "api" / "versions"
    d.mkdir(parents=True)
    f = d / "v2.py"
    f.write_text("API_VERSION = 2\n")
    assert _is_autogen_file(f, tmp_path, set()) is False


def test_openapi_generator_footprint(tmp_path):
    d = tmp_path / "src" / "api"
    d.mkdir(parents=True)
    (d / ".openapi-generator").mkdir()
    f = d / "client.ts"
    f.write_text("export class Client {}\n")
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_footprint_in_ancestor_dir(tmp_path):
    d = tmp_path / "src" / "api"
    (d / "models").mkdir(parents=True)
    (d / ".openapi-generator-ignore").write_text("")
    f = d / "models" / "user.ts"
    f.write_text("export interface User {}\n")
    assert _is_autogen_file(f, tmp_path, set()) is True


# ---------------------------------------------------------------------------
# Shape heuristics (minified / dump-like files)
# ---------------------------------------------------------------------------

def test_minified_single_line_is_autogen(tmp_path):
    f = tmp_path / "app.js"
    f.write_text("var a=1;" * 4000)  # 32 KB, one line
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_long_average_line_is_autogen(tmp_path):
    f = tmp_path / "data.js"
    f.write_text("\n".join(["x" * 400] * 100))  # 100 lines, 400 B each
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_normal_large_file_is_not_autogen(tmp_path):
    f = tmp_path / "big_module.py"
    f.write_text("\n".join(f"value_{i} = {i}" for i in range(2000)))  # ~30 KB
    assert _is_autogen_file(f, tmp_path, set()) is False


def test_small_file_skips_shape_check(tmp_path):
    f = tmp_path / "one_liner.js"
    f.write_text("var a=1;" * 100)  # 800 B single line — below the size floor
    assert _is_autogen_file(f, tmp_path, set()) is False


# ---------------------------------------------------------------------------
# SQL dump detection
# ---------------------------------------------------------------------------

def test_sql_dump_by_banner(tmp_path):
    f = tmp_path / "backup.sql"
    f.write_text("-- MySQL dump 10.13\nCREATE TABLE t (id INT);\n")
    assert _is_sql_dump(f) is True


def test_sql_dump_by_insert_rows(tmp_path):
    rows = "\n".join(f"INSERT INTO t VALUES ({i});" for i in range(60))
    f = tmp_path / "seed.sql"
    f.write_text("CREATE TABLE t (id INT);\n" + rows + "\n")
    assert _is_sql_dump(f) is True
    assert _is_autogen_file(f, tmp_path, set()) is True


def test_sql_migration_is_not_dump(tmp_path):
    f = tmp_path / "001_create_users.sql"
    f.write_text(
        "CREATE TABLE users (\n  id SERIAL PRIMARY KEY,\n  name TEXT\n);\n"
        "CREATE INDEX idx_users_name ON users (name);\n"
    )
    assert _is_sql_dump(f) is False
    assert _is_autogen_file(f, tmp_path, set()) is False


# ---------------------------------------------------------------------------
# Android res XML rule
# ---------------------------------------------------------------------------

def test_android_layout_xml_is_code(tmp_path):
    f = tmp_path / "app" / "src" / "main" / "res" / "layout" / "activity_main.xml"
    f.parent.mkdir(parents=True)
    f.write_text("<LinearLayout/>\n")
    assert _is_android_res_xml(f, tmp_path) is True


def test_android_values_qualifier_is_code(tmp_path):
    f = tmp_path / "res" / "values-night" / "colors.xml"
    f.parent.mkdir(parents=True)
    f.write_text("<resources/>\n")
    assert _is_android_res_xml(f, tmp_path) is True


def test_android_manifest_is_code(tmp_path):
    f = tmp_path / "app" / "src" / "main" / "AndroidManifest.xml"
    f.parent.mkdir(parents=True)
    f.write_text("<manifest/>\n")
    assert _is_android_res_xml(f, tmp_path) is True


def test_plain_data_xml_is_not_code(tmp_path):
    f = tmp_path / "data" / "export.xml"
    f.parent.mkdir(parents=True)
    f.write_text("<items/>\n")
    assert _is_android_res_xml(f, tmp_path) is False


# ---------------------------------------------------------------------------
# clean_logical_loc integration (scc)
# ---------------------------------------------------------------------------

def _make_allowed_files() -> AllowedFiles:
    return AllowedFiles(AllowedFilesConfig(config_file=_TOML_PATH))


@pytest.fixture
def clean_repo(tmp_path):
    """Synthetic repo exercising every clean_logical_loc rule:

    src/main.py           — code, counted
    src/style.css         — markup counts as code, counted
    src/data.json         — non-code language, dropped
    res/layout/main.xml   — Android res XML, counted
    config/feed.xml       — plain XML, dropped
    db/backup.sql         — dump (banner), dropped
    bitrix/core.php       — CMS core dir, excluded by clean list only
    """
    repo = tmp_path / "repo"
    for d in ("src", "res/layout", "config", "db", "bitrix"):
        (repo / d).mkdir(parents=True)
    (repo / "src" / "main.py").write_text("\n".join(f"a_{i} = {i}" for i in range(10)) + "\n")
    (repo / "src" / "style.css").write_text(".cls {\n  color: red;\n}\n")
    (repo / "src" / "data.json").write_text('{\n  "k": 1\n}\n')
    (repo / "res" / "layout" / "main.xml").write_text("<LinearLayout>\n</LinearLayout>\n")
    (repo / "config" / "feed.xml").write_text("<items>\n<item/>\n</items>\n")
    (repo / "db" / "backup.sql").write_text("-- MySQL dump 10.13\nCREATE TABLE t (id INT);\n")
    (repo / "bitrix" / "core.php").write_text("<?php\n" + "\n".join(f"$b{i} = {i};" for i in range(50)) + "\n")
    run(["git", "init"], cwd=repo, check=True, capture_output=True)
    return repo


def test_clean_logical_loc_rules(clean_repo):
    settings = load_app_settings(_TOML_PATH)
    total = get_clean_logical_loc(
        clean_repo,
        exclude_dirs=list(settings.metrics.clean_scc_exclude_dirs),
        non_code_languages=set(settings.metrics.clean_non_code_languages),
    )
    # 10 (main.py) + 3 (style.css) + 2 (res XML); json/plain xml/sql dump/bitrix dropped
    assert total == 15


def test_clean_metric_vs_logical(clean_repo):
    settings = load_app_settings(_TOML_PATH)
    ctx = RepoContext(
        repo_path=clean_repo,
        settings=settings,
        tree_sitter=None,
        allowed_files=_make_allowed_files(),
    )
    clean = CleanLogicalLocMetric().compute(ctx)
    logical = LogicalLocMetric().compute(ctx)
    assert clean == 15
    # logical counts the CMS core, data json, plain XML and the SQL dump too
    assert clean < logical
